spring.application.name=backend
server.port=${SERVER_PORT:8080}
app.base-url=${APP_BASE_URL:http://localhost:8080}

git.storage.path=${GIT_STORAGE_PATH:git-storage}

#spring.datasource.url=jdbc:postgresql://localhost:5432/gitclone
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/gitclone}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gituser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:gitpassword}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwtSecret=${APP_JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A7134743777217A25432A462D4A614E635266556A586E3272357538782F413F4428472B4B}
app.jwtExpirationInMs=${APP_JWT_EXPIRATION_IN_MS:315569259747}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:sebimarcus23@gmail.com}
spring.mail.password=${MAIL_PASSWORD:wzmxjqpshccdmadd}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=${APP_FRONTEND_URL:http://localhost:4200}