spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

git.storage.path=target/test-git-storage

app.jwtSecret=5367566B53703373367639192F423F4528482B4D6251655468576D5A7134743777217A25432A462D4A614E625266556A586E3272357538782F413F4428472B4B
app.jwtExpirationInMs=3600000